migrated to express. change to accept only cid, not urls
ipfs-search/nsfw-server pull request #15
Opened 2022-02-02 20:19 UTC by femans

2022-02-03 10:19 UTC, dokterbob requested changes
Test error:   ● mozilla grapefruit jpg › should return a 200 status code

2022-02-03 10:19 UTC, dokterbob commented on package.json
>      "@tensorflow/tfjs-node": "^3.11.0",
It seems hapi could be removed here.

2022-02-03 10:19 UTC, dokterbob commented on src/nsfwServerHapi.js
> +// eslint-disable-next-line no-unused-expressions,global-require
Can't this entire file be removed now?

2022-02-03 11:45 UTC, femans commented on src/nsfwServerHapi.js
> +// eslint-disable-next-line no-unused-expressions,global-require
yes

2022-02-03 11:47 UTC, femans commented on src/nsfwServer.js
> +          (entry) => [entry.className.toLowerCase(), entry.probability],
i did an eslint fix and pushed it now

2022-02-04 09:09 UTC, femans commented
I believe the unit tests are not yet working

2022-02-10 10:45 UTC, merged